### ISSUE TITLE
Fix misusage of UniformBackgroundField

### ISSUE THREAD

**Issue by santisoler** [simpeg/user-tutorials#12]
Currently some of the magnetic tutorials are passing the `parameters` to the `UniformBackgroundField`, which is being unused in SimPEG v0.20.0. In such case, the source class will use the default values for the `amplitude`, `inclination` and `declination` arguments, ignoring the ones passed through `parameters`.

SimPEG v0.21 raises an error when passing `parameters` to the class, in order to prevent a silent misbehavior of the class.

I think we should update these tutorials: remove the `parameters` and pass the `amplitude`, `inclination` and `declination` arguments.

For example, in https://simpeg.xyz/user-tutorials/fwd-magnetics-induced-3d the definition of the source should be changed as follows:

```python
# Define the inducing field H0 = (intensity [nT], inclination [deg], declination [deg])
inclination = 90
declination = 0
strength = 50000

source_field = magnetics.sources.UniformBackgroundField(
    receiver_list=receiver_list, 
    amplitude=strength,
    inclination=inclination,
    declination=declination,
)
```

---

This issue was found after discussing a forward model that @aguspesce was running.

**Comment by lheagy** [comment]
Another item we raised in the SimPEG meeting is the question: should we have default values for `amplitude`, `inclination` and `declination`? Or require that the user sets them?
