### ISSUE TITLE
Specific authors and roles for individual notebooks

### ISSUE THREAD

**Issue by dccowan** [simpeg/user-tutorials#26]
Right now, Devin and Santi are automatically stated as authors at the beginning of all pages within GitHub tutorials. We would like to be more specific regarding the authors of each notebook and roles of contributors. See: https://mystmd.org/guide/frontmatter#in-a-jupyter-notebook for how to change authors.

**Comment by santisoler** [comment]
We could also specify roles for each author to make it clear what tasks where performed by each person.

I also suspect we could have a running list of every author in the `myst.yml`, set `id`s for each of them and then just reference them using the `id` in every notebook they authored (see https://mystmd.org/guide/frontmatter#in-a-jupyter-notebook). We might want to experiment with it.

BTW, we could also use ids for affiliations so we don't have to repeat them.
