### ISSUE TITLE
Missing `topo_2d.txt` file used in 2.5D DC Resisitivity Inversion

### ISSUE THREAD

**Issue by santisoler** [simpeg/user-tutorials#8]
While loading the data for running the 2.5D DC inversion, the first cell in [Load Data and Plot](https://simpeg.xyz/user-tutorials/inv-dcr-2d#load-data-and-plot) defines the path to a `topo_2d.txt` file. From the commented lines, this file should be in https://github.com/simpeg/user-tutorials/raw/main/assets/05-dcr/fwd_dcr_2d.tar.gz, although it isn't. Instead, there's a `topo_xyz.txt` file with three columns that makes the refinement of the tree mesh (see [Designing a (Tree) Mesh](https://simpeg.xyz/user-tutorials/inv-dcr-2d#designing-a-tree-mesh)) to fail.

**Comment by dccowan** [comment]
Done
